### ISSUE TITLE
Feature request: Remove morph as a default action.

### ISSUE THREAD

**Issue by minimul** [marcoroth/turbo_power#43]
I'd speculate (I admit that this surmise is based on no actually data but just a professional hunch) that the `morph` custom action is rarely used but in turn carries a dependency, the `turbo-morph` NPM package. 

Should it not then be required but opt-in?

Thanks @marcoroth  for your consideration.

**Comment by marcoroth** [comment]
Ha! Ironically the `morph` custom action is the one of the most used ones, at least as far as I've seen.

I don't think we are going to remove the `morph` custom action from `turbo_power` from the time being, but maybe there's an opportunity to merge the two packages. I kept it as a separate package because of the morphdom depedency, but seems like Importmaps are not good enough to handle those kind of cases.

At least for now, I inlined turbo-morph and it's morphdom dependency into the `turbo_power` dist, so that should be good for now.

**Comment by minimul** [comment]
> Ha! Ironically the morph custom action is the one of the most used ones, at least as far as I've seen.

:)) OK, good to know!

> At least for now, I inlined turbo-morph and it's morphdom dependency into the turbo_power dist, so that should be good for now.

👍
